services:
  site-opticar:
    image: mahducosta/opticar-ec2:site-opticar
    ports:
      - "3333:3333"
    networks:
      - rede-opticar
    depends_on:
      - opticarFrio
      - opticarQuente

  api-jira:
    image: mahducosta/opticar-ec2:api-jira
    networks:
      - rede-opticar
    container_name: api-jira
    depends_on:
      - opticarFrio
      - opticarQuente

  api-intermediaria:
    image: mahducosta/opticar-ec2:api-intermediaria
    ports:
      - "5000:5000"
    networks:
      - rede-opticar
    container_name: api-intermediaria
    depends_on:
      - opticarFrio
      - opticarQuente

  opticarQuente:
    image: mahducosta/opticar-ec2:db-quente
    ports:
      - "3307:3306"
    networks:
      - rede-opticar
    container_name: opticarQuente
    depends_on:
      - opticarFrio

  opticarFrio:
    image: mahducosta/opticar-ec2:db-frio
    ports:
      - "3306:3306"
    networks:
      - rede-opticar
    container_name: opticarFrio

networks:
  rede-opticar:
    driver: bridge
    name: rede-opticar
